apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluatorservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evaluatorservice
  template:
    metadata:
      labels:
        app: evaluatorservice
    spec:
      containers:
      - name: evaluatorservice
        image: askattilla/rfb-evaluator:50f9a9bf9b6f0d2bf3f84e2fe6cae117f5d7f074
        ports:
        - containerPort: 5000