apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluatorservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evaluatorservice
  template:
    metadata:
      labels:
        app: evaluatorservice
    spec:
      containers:
      - name: evaluatorservice
        image: askattilla/rfb-evaluator:315e77eea7f3c8cc9fc5040b313c1b9b355b8215
        ports:
        - containerPort: 5000