apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluatorservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evaluatorservice
  template:
    metadata:
      labels:
        app: evaluatorservice
    spec:
      containers:
      - name: evaluatorservice
        image: askattilla/rfb-evaluator:db3ddeb1e737c191b0ce7af33de813836f6bca37
        ports:
        - containerPort: 5000