apiVersion: v1
kind: Service
metadata:
  name: evaluatorservice-svc
  namespace: default
spec:
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: evaluatorservice
  sessionAffinity: None
  type: ClusterIP